export const INDUSTRY_OPTIONS = [
  "Technology",
  "Finance",
  "Banking",
  "Insurance",
  "Healthcare",
  "Pharmaceuticals",
  "Education",
  "Telecommunications",
  "Retail",
  "E-commerce",
  "Hospitality",
  "Tourism",
  "Manufacturing",
  "Construction",
  "Real Estate",
  "Logistics",
  "Transportation",
  "Energy",
  "Agriculture",
  "Food & Beverage",
  "Media",
  "Marketing",
  "Advertising",
  "Legal Services",
  "Government",
  "Nonprofit",
  "Human Resources",
  "Consulting",
  "Automotive",
  "Security Services",
];
